name: Cleanup on PR merge
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    env: 
      AWS_REGION: "ap-northeast-1"
      SUB_DIRECTORY: ${{ github.repository_owner }}_${{ github.event.number }}
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Remove S3 Directory
      run: aws s3 rm s3://gha-s3-sample/${{ env.SUB_DIRECTORY }} --recursive
