name: Cleanup on PR merge
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env: 
      AWS_REGION: "ap-northeast-1"
      SUB_DIRECTORY: ${{ github.repository_owner }}_${{ github.event.number }}
    steps:
    - name: Remove S3 Directory
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws s3 rm s3://gha-s3-sample/${{ env.SUB_DIRECTORY }} --recursive
